/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const ToolsDesktopappLazyImport = createFileRoute('/tools/desktopapp')()
const ToolsCompositionanalyzerLazyImport = createFileRoute(
  '/tools/compositionanalyzer',
)()
const ToolsChampionstatsLazyImport = createFileRoute('/tools/championstats')()
const ToolsBestbansLazyImport = createFileRoute('/tools/bestbans')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ToolsDesktopappLazyRoute = ToolsDesktopappLazyImport.update({
  path: '/tools/desktopapp',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/tools/desktopapp.lazy').then((d) => d.Route),
)

const ToolsCompositionanalyzerLazyRoute =
  ToolsCompositionanalyzerLazyImport.update({
    path: '/tools/compositionanalyzer',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/tools/compositionanalyzer.lazy').then((d) => d.Route),
  )

const ToolsChampionstatsLazyRoute = ToolsChampionstatsLazyImport.update({
  path: '/tools/championstats',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/tools/championstats.lazy').then((d) => d.Route),
)

const ToolsBestbansLazyRoute = ToolsBestbansLazyImport.update({
  path: '/tools/bestbans',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/tools/bestbans.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/tools/bestbans': {
      preLoaderRoute: typeof ToolsBestbansLazyImport
      parentRoute: typeof rootRoute
    }
    '/tools/championstats': {
      preLoaderRoute: typeof ToolsChampionstatsLazyImport
      parentRoute: typeof rootRoute
    }
    '/tools/compositionanalyzer': {
      preLoaderRoute: typeof ToolsCompositionanalyzerLazyImport
      parentRoute: typeof rootRoute
    }
    '/tools/desktopapp': {
      preLoaderRoute: typeof ToolsDesktopappLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  ToolsBestbansLazyRoute,
  ToolsChampionstatsLazyRoute,
  ToolsCompositionanalyzerLazyRoute,
  ToolsDesktopappLazyRoute,
])

/* prettier-ignore-end */
