# fly.toml app configuration file generated for tiltseeker on 2024-04-24T01:27:11-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tiltseeker'
primary_region = 'ord'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[env]
  PORT = '8080'

[mounts]
  source = 'tiltseeker_db'
  destination = '/data'
  initial_size = '3GB'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'
